# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

abbr --add k "kubectl"
abbr --add ksys "kubectl --namespace=kube-system"
abbr --add ka "kubectl apply --recursive -f"
abbr --add ksysa "kubectl --namespace=kube-system apply --recursive -f"
abbr --add kak "kubectl apply -k"
abbr --add kk "kubectl kustomize"
abbr --add kex "kubectl exec -i -t"
abbr --add ksysex "kubectl --namespace=kube-system exec -i -t"
abbr --add klo "kubectl logs -f"
abbr --add ksyslo "kubectl --namespace=kube-system logs -f"
abbr --add klop "kubectl logs -f -p"
abbr --add ksyslop "kubectl --namespace=kube-system logs -f -p"
abbr --add ke "kubectl edit"
abbr --add ksyse "kubectl --namespace=kube-system edit"
abbr --add krr "kubectl rollout restart"
abbr --add ksysrr "kubectl --namespace=kube-system rollout restart"
abbr --add krs "kubectl rollout status"
abbr --add ksysrs "kubectl --namespace=kube-system rollout status"
abbr --add ks "kubectl scale"
abbr --add ksyss "kubectl --namespace=kube-system scale"
abbr --add kp "kubectl proxy"
abbr --add kpf "kubectl port-forward"
abbr --add kg "kubectl get"
abbr --add ksysg "kubectl --namespace=kube-system get"
abbr --add kd "kubectl describe"
abbr --add ksysd "kubectl --namespace=kube-system describe"
abbr --add krm "kubectl delete"
abbr --add ksysrm "kubectl --namespace=kube-system delete"
abbr --add krun "kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t"
abbr --add ksysrun "kubectl --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t"
abbr --add kepo "kubectl edit pods"
abbr --add ksysepo "kubectl --namespace=kube-system edit pods"
abbr --add kgpo "kubectl get pods"
abbr --add ksysgpo "kubectl --namespace=kube-system get pods"
abbr --add kdpo "kubectl describe pods"
abbr --add ksysdpo "kubectl --namespace=kube-system describe pods"
abbr --add krmpo "kubectl delete pods"
abbr --add ksysrmpo "kubectl --namespace=kube-system delete pods"
abbr --add kedep "kubectl edit deployment"
abbr --add ksysedep "kubectl --namespace=kube-system edit deployment"
abbr --add krrdep "kubectl rollout restart deployment"
abbr --add ksysrrdep "kubectl --namespace=kube-system rollout restart deployment"
abbr --add krsdep "kubectl rollout status deployment"
abbr --add ksysrsdep "kubectl --namespace=kube-system rollout status deployment"
abbr --add ksdep "kubectl scale deployment"
abbr --add ksyssdep "kubectl --namespace=kube-system scale deployment"
abbr --add kgdep "kubectl get deployment"
abbr --add ksysgdep "kubectl --namespace=kube-system get deployment"
abbr --add kddep "kubectl describe deployment"
abbr --add ksysddep "kubectl --namespace=kube-system describe deployment"
abbr --add krmdep "kubectl delete deployment"
abbr --add ksysrmdep "kubectl --namespace=kube-system delete deployment"
abbr --add keds "kubectl edit daemonset"
abbr --add ksyseds "kubectl --namespace=kube-system edit daemonset"
abbr --add krrds "kubectl rollout restart daemonset"
abbr --add ksysrrds "kubectl --namespace=kube-system rollout restart daemonset"
abbr --add krsds "kubectl rollout status daemonset"
abbr --add ksysrsds "kubectl --namespace=kube-system rollout status daemonset"
abbr --add kgds "kubectl get daemonset"
abbr --add ksysgds "kubectl --namespace=kube-system get daemonset"
abbr --add kdds "kubectl describe daemonset"
abbr --add ksysdds "kubectl --namespace=kube-system describe daemonset"
abbr --add krmds "kubectl delete daemonset"
abbr --add ksysrmds "kubectl --namespace=kube-system delete daemonset"
abbr --add kesvc "kubectl edit service"
abbr --add ksysesvc "kubectl --namespace=kube-system edit service"
abbr --add kgsvc "kubectl get service"
abbr --add ksysgsvc "kubectl --namespace=kube-system get service"
abbr --add kdsvc "kubectl describe service"
abbr --add ksysdsvc "kubectl --namespace=kube-system describe service"
abbr --add krmsvc "kubectl delete service"
abbr --add ksysrmsvc "kubectl --namespace=kube-system delete service"
abbr --add keing "kubectl edit ingress"
abbr --add ksyseing "kubectl --namespace=kube-system edit ingress"
abbr --add kging "kubectl get ingress"
abbr --add ksysging "kubectl --namespace=kube-system get ingress"
abbr --add kding "kubectl describe ingress"
abbr --add ksysding "kubectl --namespace=kube-system describe ingress"
abbr --add krming "kubectl delete ingress"
abbr --add ksysrming "kubectl --namespace=kube-system delete ingress"
abbr --add kecm "kubectl edit configmap"
abbr --add ksysecm "kubectl --namespace=kube-system edit configmap"
abbr --add kgcm "kubectl get configmap"
abbr --add ksysgcm "kubectl --namespace=kube-system get configmap"
abbr --add kdcm "kubectl describe configmap"
abbr --add ksysdcm "kubectl --namespace=kube-system describe configmap"
abbr --add krmcm "kubectl delete configmap"
abbr --add ksysrmcm "kubectl --namespace=kube-system delete configmap"
abbr --add kesec "kubectl edit secret"
abbr --add ksysesec "kubectl --namespace=kube-system edit secret"
abbr --add kgsec "kubectl get secret"
abbr --add ksysgsec "kubectl --namespace=kube-system get secret"
abbr --add kdsec "kubectl describe secret"
abbr --add ksysdsec "kubectl --namespace=kube-system describe secret"
abbr --add krmsec "kubectl delete secret"
abbr --add ksysrmsec "kubectl --namespace=kube-system delete secret"
abbr --add kgpvc "kubectl get pvc"
abbr --add ksysgpvc "kubectl --namespace=kube-system get pvc"
abbr --add kdpvc "kubectl describe pvc"
abbr --add ksysdpvc "kubectl --namespace=kube-system describe pvc"
abbr --add krmpvc "kubectl delete pvc"
abbr --add ksysrmpvc "kubectl --namespace=kube-system delete pvc"
abbr --add kgnad "kubectl get net-attach-def"
abbr --add ksysgnad "kubectl --namespace=kube-system get net-attach-def"
abbr --add kdnad "kubectl describe net-attach-def"
abbr --add ksysdnad "kubectl --namespace=kube-system describe net-attach-def"
abbr --add krmnad "kubectl delete net-attach-def"
abbr --add ksysrmnad "kubectl --namespace=kube-system delete net-attach-def"
abbr --add kgno "kubectl get nodes"
abbr --add kdno "kubectl describe nodes"
abbr --add kgrs "kubectl get replicaset"
abbr --add kdrs "kubectl describe replicaset"
abbr --add kgns "kubectl get namespaces"
abbr --add kdns "kubectl describe namespaces"
abbr --add krmns "kubectl delete namespaces"
abbr --add kgoyaml "kubectl get -o=yaml"
abbr --add ksysgoyaml "kubectl --namespace=kube-system get -o=yaml"
abbr --add kgpooyaml "kubectl get pods -o=yaml"
abbr --add ksysgpooyaml "kubectl --namespace=kube-system get pods -o=yaml"
abbr --add kgdepoyaml "kubectl get deployment -o=yaml"
abbr --add ksysgdepoyaml "kubectl --namespace=kube-system get deployment -o=yaml"
abbr --add kgdsoyaml "kubectl get daemonset -o=yaml"
abbr --add ksysgdsoyaml "kubectl --namespace=kube-system get daemonset -o=yaml"
abbr --add kgsvcoyaml "kubectl get service -o=yaml"
abbr --add ksysgsvcoyaml "kubectl --namespace=kube-system get service -o=yaml"
abbr --add kgingoyaml "kubectl get ingress -o=yaml"
abbr --add ksysgingoyaml "kubectl --namespace=kube-system get ingress -o=yaml"
abbr --add kgcmoyaml "kubectl get configmap -o=yaml"
abbr --add ksysgcmoyaml "kubectl --namespace=kube-system get configmap -o=yaml"
abbr --add kgsecoyaml "kubectl get secret -o=yaml"
abbr --add ksysgsecoyaml "kubectl --namespace=kube-system get secret -o=yaml"
abbr --add kgpvcoyaml "kubectl get pvc -o=yaml"
abbr --add ksysgpvcoyaml "kubectl --namespace=kube-system get pvc -o=yaml"
abbr --add kgnadoyaml "kubectl get net-attach-def -o=yaml"
abbr --add ksysgnadoyaml "kubectl --namespace=kube-system get net-attach-def -o=yaml"
abbr --add kgnooyaml "kubectl get nodes -o=yaml"
abbr --add kgrsoyaml "kubectl get replicaset -o=yaml"
abbr --add kgnsoyaml "kubectl get namespaces -o=yaml"
abbr --add kgowide "kubectl get -o=wide"
abbr --add ksysgowide "kubectl --namespace=kube-system get -o=wide"
abbr --add kgpoowide "kubectl get pods -o=wide"
abbr --add ksysgpoowide "kubectl --namespace=kube-system get pods -o=wide"
abbr --add kgdepowide "kubectl get deployment -o=wide"
abbr --add ksysgdepowide "kubectl --namespace=kube-system get deployment -o=wide"
abbr --add kgdsowide "kubectl get daemonset -o=wide"
abbr --add ksysgdsowide "kubectl --namespace=kube-system get daemonset -o=wide"
abbr --add kgsvcowide "kubectl get service -o=wide"
abbr --add ksysgsvcowide "kubectl --namespace=kube-system get service -o=wide"
abbr --add kgingowide "kubectl get ingress -o=wide"
abbr --add ksysgingowide "kubectl --namespace=kube-system get ingress -o=wide"
abbr --add kgcmowide "kubectl get configmap -o=wide"
abbr --add ksysgcmowide "kubectl --namespace=kube-system get configmap -o=wide"
abbr --add kgsecowide "kubectl get secret -o=wide"
abbr --add ksysgsecowide "kubectl --namespace=kube-system get secret -o=wide"
abbr --add kgpvcowide "kubectl get pvc -o=wide"
abbr --add ksysgpvcowide "kubectl --namespace=kube-system get pvc -o=wide"
abbr --add kgnadowide "kubectl get net-attach-def -o=wide"
abbr --add ksysgnadowide "kubectl --namespace=kube-system get net-attach-def -o=wide"
abbr --add kgnoowide "kubectl get nodes -o=wide"
abbr --add kgrsowide "kubectl get replicaset -o=wide"
abbr --add kgnsowide "kubectl get namespaces -o=wide"
abbr --add kgojson "kubectl get -o=json"
abbr --add ksysgojson "kubectl --namespace=kube-system get -o=json"
abbr --add kgpoojson "kubectl get pods -o=json"
abbr --add ksysgpoojson "kubectl --namespace=kube-system get pods -o=json"
abbr --add kgdepojson "kubectl get deployment -o=json"
abbr --add ksysgdepojson "kubectl --namespace=kube-system get deployment -o=json"
abbr --add kgdsojson "kubectl get daemonset -o=json"
abbr --add ksysgdsojson "kubectl --namespace=kube-system get daemonset -o=json"
abbr --add kgsvcojson "kubectl get service -o=json"
abbr --add ksysgsvcojson "kubectl --namespace=kube-system get service -o=json"
abbr --add kgingojson "kubectl get ingress -o=json"
abbr --add ksysgingojson "kubectl --namespace=kube-system get ingress -o=json"
abbr --add kgcmojson "kubectl get configmap -o=json"
abbr --add ksysgcmojson "kubectl --namespace=kube-system get configmap -o=json"
abbr --add kgsecojson "kubectl get secret -o=json"
abbr --add ksysgsecojson "kubectl --namespace=kube-system get secret -o=json"
abbr --add kgpvcojson "kubectl get pvc -o=json"
abbr --add ksysgpvcojson "kubectl --namespace=kube-system get pvc -o=json"
abbr --add kgnadojson "kubectl get net-attach-def -o=json"
abbr --add ksysgnadojson "kubectl --namespace=kube-system get net-attach-def -o=json"
abbr --add kgnoojson "kubectl get nodes -o=json"
abbr --add kgrsojson "kubectl get replicaset -o=json"
abbr --add kgnsojson "kubectl get namespaces -o=json"
abbr --add kgall "kubectl get --all-namespaces"
abbr --add kdall "kubectl describe --all-namespaces"
abbr --add kgpoall "kubectl get pods --all-namespaces"
abbr --add kdpoall "kubectl describe pods --all-namespaces"
abbr --add kgdepall "kubectl get deployment --all-namespaces"
abbr --add kddepall "kubectl describe deployment --all-namespaces"
abbr --add kgdsall "kubectl get daemonset --all-namespaces"
abbr --add kddsall "kubectl describe daemonset --all-namespaces"
abbr --add kgsvcall "kubectl get service --all-namespaces"
abbr --add kdsvcall "kubectl describe service --all-namespaces"
abbr --add kgingall "kubectl get ingress --all-namespaces"
abbr --add kdingall "kubectl describe ingress --all-namespaces"
abbr --add kgcmall "kubectl get configmap --all-namespaces"
abbr --add kdcmall "kubectl describe configmap --all-namespaces"
abbr --add kgsecall "kubectl get secret --all-namespaces"
abbr --add kdsecall "kubectl describe secret --all-namespaces"
abbr --add kgpvcall "kubectl get pvc --all-namespaces"
abbr --add kdpvcall "kubectl describe pvc --all-namespaces"
abbr --add kgnadall "kubectl get net-attach-def --all-namespaces"
abbr --add kdnadall "kubectl describe net-attach-def --all-namespaces"
abbr --add kgrsall "kubectl get replicaset --all-namespaces"
abbr --add kdrsall "kubectl describe replicaset --all-namespaces"
abbr --add kgnsall "kubectl get namespaces --all-namespaces"
abbr --add kdnsall "kubectl describe namespaces --all-namespaces"
abbr --add kgsl "kubectl get --show-labels"
abbr --add ksysgsl "kubectl --namespace=kube-system get --show-labels"
abbr --add kgposl "kubectl get pods --show-labels"
abbr --add ksysgposl "kubectl --namespace=kube-system get pods --show-labels"
abbr --add kgdepsl "kubectl get deployment --show-labels"
abbr --add ksysgdepsl "kubectl --namespace=kube-system get deployment --show-labels"
abbr --add kgdssl "kubectl get daemonset --show-labels"
abbr --add ksysgdssl "kubectl --namespace=kube-system get daemonset --show-labels"
abbr --add kgsvcsl "kubectl get service --show-labels"
abbr --add ksysgsvcsl "kubectl --namespace=kube-system get service --show-labels"
abbr --add kgingsl "kubectl get ingress --show-labels"
abbr --add ksysgingsl "kubectl --namespace=kube-system get ingress --show-labels"
abbr --add kgcmsl "kubectl get configmap --show-labels"
abbr --add ksysgcmsl "kubectl --namespace=kube-system get configmap --show-labels"
abbr --add kgsecsl "kubectl get secret --show-labels"
abbr --add ksysgsecsl "kubectl --namespace=kube-system get secret --show-labels"
abbr --add kgpvcsl "kubectl get pvc --show-labels"
abbr --add ksysgpvcsl "kubectl --namespace=kube-system get pvc --show-labels"
abbr --add kgnadsl "kubectl get net-attach-def --show-labels"
abbr --add ksysgnadsl "kubectl --namespace=kube-system get net-attach-def --show-labels"
abbr --add kgnosl "kubectl get nodes --show-labels"
abbr --add kgrssl "kubectl get replicaset --show-labels"
abbr --add kgnssl "kubectl get namespaces --show-labels"
abbr --add krmall "kubectl delete --all"
abbr --add ksysrmall "kubectl --namespace=kube-system delete --all"
abbr --add krmpoall "kubectl delete pods --all"
abbr --add ksysrmpoall "kubectl --namespace=kube-system delete pods --all"
abbr --add krmdepall "kubectl delete deployment --all"
abbr --add ksysrmdepall "kubectl --namespace=kube-system delete deployment --all"
abbr --add krmdsall "kubectl delete daemonset --all"
abbr --add ksysrmdsall "kubectl --namespace=kube-system delete daemonset --all"
abbr --add krmsvcall "kubectl delete service --all"
abbr --add ksysrmsvcall "kubectl --namespace=kube-system delete service --all"
abbr --add krmingall "kubectl delete ingress --all"
abbr --add ksysrmingall "kubectl --namespace=kube-system delete ingress --all"
abbr --add krmcmall "kubectl delete configmap --all"
abbr --add ksysrmcmall "kubectl --namespace=kube-system delete configmap --all"
abbr --add krmsecall "kubectl delete secret --all"
abbr --add ksysrmsecall "kubectl --namespace=kube-system delete secret --all"
abbr --add krmpvcall "kubectl delete pvc --all"
abbr --add ksysrmpvcall "kubectl --namespace=kube-system delete pvc --all"
abbr --add krmnadall "kubectl delete net-attach-def --all"
abbr --add ksysrmnadall "kubectl --namespace=kube-system delete net-attach-def --all"
abbr --add krmnsall "kubectl delete namespaces --all"
abbr --add kgw "kubectl get --watch"
abbr --add ksysgw "kubectl --namespace=kube-system get --watch"
abbr --add kgpow "kubectl get pods --watch"
abbr --add ksysgpow "kubectl --namespace=kube-system get pods --watch"
abbr --add kgdepw "kubectl get deployment --watch"
abbr --add ksysgdepw "kubectl --namespace=kube-system get deployment --watch"
abbr --add kgdsw "kubectl get daemonset --watch"
abbr --add ksysgdsw "kubectl --namespace=kube-system get daemonset --watch"
abbr --add kgsvcw "kubectl get service --watch"
abbr --add ksysgsvcw "kubectl --namespace=kube-system get service --watch"
abbr --add kgingw "kubectl get ingress --watch"
abbr --add ksysgingw "kubectl --namespace=kube-system get ingress --watch"
abbr --add kgcmw "kubectl get configmap --watch"
abbr --add ksysgcmw "kubectl --namespace=kube-system get configmap --watch"
abbr --add kgsecw "kubectl get secret --watch"
abbr --add ksysgsecw "kubectl --namespace=kube-system get secret --watch"
abbr --add kgpvcw "kubectl get pvc --watch"
abbr --add ksysgpvcw "kubectl --namespace=kube-system get pvc --watch"
abbr --add kgnadw "kubectl get net-attach-def --watch"
abbr --add ksysgnadw "kubectl --namespace=kube-system get net-attach-def --watch"
abbr --add kgnow "kubectl get nodes --watch"
abbr --add kgrsw "kubectl get replicaset --watch"
abbr --add kgnsw "kubectl get namespaces --watch"
abbr --add kgoyamlall "kubectl get -o=yaml --all-namespaces"
abbr --add kgpooyamlall "kubectl get pods -o=yaml --all-namespaces"
abbr --add kgdepoyamlall "kubectl get deployment -o=yaml --all-namespaces"
abbr --add kgdsoyamlall "kubectl get daemonset -o=yaml --all-namespaces"
abbr --add kgsvcoyamlall "kubectl get service -o=yaml --all-namespaces"
abbr --add kgingoyamlall "kubectl get ingress -o=yaml --all-namespaces"
abbr --add kgcmoyamlall "kubectl get configmap -o=yaml --all-namespaces"
abbr --add kgsecoyamlall "kubectl get secret -o=yaml --all-namespaces"
abbr --add kgpvcoyamlall "kubectl get pvc -o=yaml --all-namespaces"
abbr --add kgnadoyamlall "kubectl get net-attach-def -o=yaml --all-namespaces"
abbr --add kgrsoyamlall "kubectl get replicaset -o=yaml --all-namespaces"
abbr --add kgnsoyamlall "kubectl get namespaces -o=yaml --all-namespaces"
abbr --add kgalloyaml "kubectl get --all-namespaces -o=yaml"
abbr --add kgpoalloyaml "kubectl get pods --all-namespaces -o=yaml"
abbr --add kgdepalloyaml "kubectl get deployment --all-namespaces -o=yaml"
abbr --add kgdsalloyaml "kubectl get daemonset --all-namespaces -o=yaml"
abbr --add kgsvcalloyaml "kubectl get service --all-namespaces -o=yaml"
abbr --add kgingalloyaml "kubectl get ingress --all-namespaces -o=yaml"
abbr --add kgcmalloyaml "kubectl get configmap --all-namespaces -o=yaml"
abbr --add kgsecalloyaml "kubectl get secret --all-namespaces -o=yaml"
abbr --add kgpvcalloyaml "kubectl get pvc --all-namespaces -o=yaml"
abbr --add kgnadalloyaml "kubectl get net-attach-def --all-namespaces -o=yaml"
abbr --add kgrsalloyaml "kubectl get replicaset --all-namespaces -o=yaml"
abbr --add kgnsalloyaml "kubectl get namespaces --all-namespaces -o=yaml"
abbr --add kgowideall "kubectl get -o=wide --all-namespaces"
abbr --add kgpoowideall "kubectl get pods -o=wide --all-namespaces"
abbr --add kgdepowideall "kubectl get deployment -o=wide --all-namespaces"
abbr --add kgdsowideall "kubectl get daemonset -o=wide --all-namespaces"
abbr --add kgsvcowideall "kubectl get service -o=wide --all-namespaces"
abbr --add kgingowideall "kubectl get ingress -o=wide --all-namespaces"
abbr --add kgcmowideall "kubectl get configmap -o=wide --all-namespaces"
abbr --add kgsecowideall "kubectl get secret -o=wide --all-namespaces"
abbr --add kgpvcowideall "kubectl get pvc -o=wide --all-namespaces"
abbr --add kgnadowideall "kubectl get net-attach-def -o=wide --all-namespaces"
abbr --add kgrsowideall "kubectl get replicaset -o=wide --all-namespaces"
abbr --add kgnsowideall "kubectl get namespaces -o=wide --all-namespaces"
abbr --add kgallowide "kubectl get --all-namespaces -o=wide"
abbr --add kgpoallowide "kubectl get pods --all-namespaces -o=wide"
abbr --add kgdepallowide "kubectl get deployment --all-namespaces -o=wide"
abbr --add kgdsallowide "kubectl get daemonset --all-namespaces -o=wide"
abbr --add kgsvcallowide "kubectl get service --all-namespaces -o=wide"
abbr --add kgingallowide "kubectl get ingress --all-namespaces -o=wide"
abbr --add kgcmallowide "kubectl get configmap --all-namespaces -o=wide"
abbr --add kgsecallowide "kubectl get secret --all-namespaces -o=wide"
abbr --add kgpvcallowide "kubectl get pvc --all-namespaces -o=wide"
abbr --add kgnadallowide "kubectl get net-attach-def --all-namespaces -o=wide"
abbr --add kgrsallowide "kubectl get replicaset --all-namespaces -o=wide"
abbr --add kgnsallowide "kubectl get namespaces --all-namespaces -o=wide"
abbr --add kgowidesl "kubectl get -o=wide --show-labels"
abbr --add ksysgowidesl "kubectl --namespace=kube-system get -o=wide --show-labels"
abbr --add kgpoowidesl "kubectl get pods -o=wide --show-labels"
abbr --add ksysgpoowidesl "kubectl --namespace=kube-system get pods -o=wide --show-labels"
abbr --add kgdepowidesl "kubectl get deployment -o=wide --show-labels"
abbr --add ksysgdepowidesl "kubectl --namespace=kube-system get deployment -o=wide --show-labels"
abbr --add kgdsowidesl "kubectl get daemonset -o=wide --show-labels"
abbr --add ksysgdsowidesl "kubectl --namespace=kube-system get daemonset -o=wide --show-labels"
abbr --add kgsvcowidesl "kubectl get service -o=wide --show-labels"
abbr --add ksysgsvcowidesl "kubectl --namespace=kube-system get service -o=wide --show-labels"
abbr --add kgingowidesl "kubectl get ingress -o=wide --show-labels"
abbr --add ksysgingowidesl "kubectl --namespace=kube-system get ingress -o=wide --show-labels"
abbr --add kgcmowidesl "kubectl get configmap -o=wide --show-labels"
abbr --add ksysgcmowidesl "kubectl --namespace=kube-system get configmap -o=wide --show-labels"
abbr --add kgsecowidesl "kubectl get secret -o=wide --show-labels"
abbr --add ksysgsecowidesl "kubectl --namespace=kube-system get secret -o=wide --show-labels"
abbr --add kgpvcowidesl "kubectl get pvc -o=wide --show-labels"
abbr --add ksysgpvcowidesl "kubectl --namespace=kube-system get pvc -o=wide --show-labels"
abbr --add kgnadowidesl "kubectl get net-attach-def -o=wide --show-labels"
abbr --add ksysgnadowidesl "kubectl --namespace=kube-system get net-attach-def -o=wide --show-labels"
abbr --add kgnoowidesl "kubectl get nodes -o=wide --show-labels"
abbr --add kgrsowidesl "kubectl get replicaset -o=wide --show-labels"
abbr --add kgnsowidesl "kubectl get namespaces -o=wide --show-labels"
abbr --add kgslowide "kubectl get --show-labels -o=wide"
abbr --add ksysgslowide "kubectl --namespace=kube-system get --show-labels -o=wide"
abbr --add kgposlowide "kubectl get pods --show-labels -o=wide"
abbr --add ksysgposlowide "kubectl --namespace=kube-system get pods --show-labels -o=wide"
abbr --add kgdepslowide "kubectl get deployment --show-labels -o=wide"
abbr --add ksysgdepslowide "kubectl --namespace=kube-system get deployment --show-labels -o=wide"
abbr --add kgdsslowide "kubectl get daemonset --show-labels -o=wide"
abbr --add ksysgdsslowide "kubectl --namespace=kube-system get daemonset --show-labels -o=wide"
abbr --add kgsvcslowide "kubectl get service --show-labels -o=wide"
abbr --add ksysgsvcslowide "kubectl --namespace=kube-system get service --show-labels -o=wide"
abbr --add kgingslowide "kubectl get ingress --show-labels -o=wide"
abbr --add ksysgingslowide "kubectl --namespace=kube-system get ingress --show-labels -o=wide"
abbr --add kgcmslowide "kubectl get configmap --show-labels -o=wide"
abbr --add ksysgcmslowide "kubectl --namespace=kube-system get configmap --show-labels -o=wide"
abbr --add kgsecslowide "kubectl get secret --show-labels -o=wide"
abbr --add ksysgsecslowide "kubectl --namespace=kube-system get secret --show-labels -o=wide"
abbr --add kgpvcslowide "kubectl get pvc --show-labels -o=wide"
abbr --add ksysgpvcslowide "kubectl --namespace=kube-system get pvc --show-labels -o=wide"
abbr --add kgnadslowide "kubectl get net-attach-def --show-labels -o=wide"
abbr --add ksysgnadslowide "kubectl --namespace=kube-system get net-attach-def --show-labels -o=wide"
abbr --add kgnoslowide "kubectl get nodes --show-labels -o=wide"
abbr --add kgrsslowide "kubectl get replicaset --show-labels -o=wide"
abbr --add kgnsslowide "kubectl get namespaces --show-labels -o=wide"
abbr --add kgojsonall "kubectl get -o=json --all-namespaces"
abbr --add kgpoojsonall "kubectl get pods -o=json --all-namespaces"
abbr --add kgdepojsonall "kubectl get deployment -o=json --all-namespaces"
abbr --add kgdsojsonall "kubectl get daemonset -o=json --all-namespaces"
abbr --add kgsvcojsonall "kubectl get service -o=json --all-namespaces"
abbr --add kgingojsonall "kubectl get ingress -o=json --all-namespaces"
abbr --add kgcmojsonall "kubectl get configmap -o=json --all-namespaces"
abbr --add kgsecojsonall "kubectl get secret -o=json --all-namespaces"
abbr --add kgpvcojsonall "kubectl get pvc -o=json --all-namespaces"
abbr --add kgnadojsonall "kubectl get net-attach-def -o=json --all-namespaces"
abbr --add kgrsojsonall "kubectl get replicaset -o=json --all-namespaces"
abbr --add kgnsojsonall "kubectl get namespaces -o=json --all-namespaces"
abbr --add kgallojson "kubectl get --all-namespaces -o=json"
abbr --add kgpoallojson "kubectl get pods --all-namespaces -o=json"
abbr --add kgdepallojson "kubectl get deployment --all-namespaces -o=json"
abbr --add kgdsallojson "kubectl get daemonset --all-namespaces -o=json"
abbr --add kgsvcallojson "kubectl get service --all-namespaces -o=json"
abbr --add kgingallojson "kubectl get ingress --all-namespaces -o=json"
abbr --add kgcmallojson "kubectl get configmap --all-namespaces -o=json"
abbr --add kgsecallojson "kubectl get secret --all-namespaces -o=json"
abbr --add kgpvcallojson "kubectl get pvc --all-namespaces -o=json"
abbr --add kgnadallojson "kubectl get net-attach-def --all-namespaces -o=json"
abbr --add kgrsallojson "kubectl get replicaset --all-namespaces -o=json"
abbr --add kgnsallojson "kubectl get namespaces --all-namespaces -o=json"
abbr --add kgallsl "kubectl get --all-namespaces --show-labels"
abbr --add kgpoallsl "kubectl get pods --all-namespaces --show-labels"
abbr --add kgdepallsl "kubectl get deployment --all-namespaces --show-labels"
abbr --add kgdsallsl "kubectl get daemonset --all-namespaces --show-labels"
abbr --add kgsvcallsl "kubectl get service --all-namespaces --show-labels"
abbr --add kgingallsl "kubectl get ingress --all-namespaces --show-labels"
abbr --add kgcmallsl "kubectl get configmap --all-namespaces --show-labels"
abbr --add kgsecallsl "kubectl get secret --all-namespaces --show-labels"
abbr --add kgpvcallsl "kubectl get pvc --all-namespaces --show-labels"
abbr --add kgnadallsl "kubectl get net-attach-def --all-namespaces --show-labels"
abbr --add kgrsallsl "kubectl get replicaset --all-namespaces --show-labels"
abbr --add kgnsallsl "kubectl get namespaces --all-namespaces --show-labels"
abbr --add kgslall "kubectl get --show-labels --all-namespaces"
abbr --add kgposlall "kubectl get pods --show-labels --all-namespaces"
abbr --add kgdepslall "kubectl get deployment --show-labels --all-namespaces"
abbr --add kgdsslall "kubectl get daemonset --show-labels --all-namespaces"
abbr --add kgsvcslall "kubectl get service --show-labels --all-namespaces"
abbr --add kgingslall "kubectl get ingress --show-labels --all-namespaces"
abbr --add kgcmslall "kubectl get configmap --show-labels --all-namespaces"
abbr --add kgsecslall "kubectl get secret --show-labels --all-namespaces"
abbr --add kgpvcslall "kubectl get pvc --show-labels --all-namespaces"
abbr --add kgnadslall "kubectl get net-attach-def --show-labels --all-namespaces"
abbr --add kgrsslall "kubectl get replicaset --show-labels --all-namespaces"
abbr --add kgnsslall "kubectl get namespaces --show-labels --all-namespaces"
abbr --add kgallw "kubectl get --all-namespaces --watch"
abbr --add kgpoallw "kubectl get pods --all-namespaces --watch"
abbr --add kgdepallw "kubectl get deployment --all-namespaces --watch"
abbr --add kgdsallw "kubectl get daemonset --all-namespaces --watch"
abbr --add kgsvcallw "kubectl get service --all-namespaces --watch"
abbr --add kgingallw "kubectl get ingress --all-namespaces --watch"
abbr --add kgcmallw "kubectl get configmap --all-namespaces --watch"
abbr --add kgsecallw "kubectl get secret --all-namespaces --watch"
abbr --add kgpvcallw "kubectl get pvc --all-namespaces --watch"
abbr --add kgnadallw "kubectl get net-attach-def --all-namespaces --watch"
abbr --add kgrsallw "kubectl get replicaset --all-namespaces --watch"
abbr --add kgnsallw "kubectl get namespaces --all-namespaces --watch"
abbr --add kgwall "kubectl get --watch --all-namespaces"
abbr --add kgpowall "kubectl get pods --watch --all-namespaces"
abbr --add kgdepwall "kubectl get deployment --watch --all-namespaces"
abbr --add kgdswall "kubectl get daemonset --watch --all-namespaces"
abbr --add kgsvcwall "kubectl get service --watch --all-namespaces"
abbr --add kgingwall "kubectl get ingress --watch --all-namespaces"
abbr --add kgcmwall "kubectl get configmap --watch --all-namespaces"
abbr --add kgsecwall "kubectl get secret --watch --all-namespaces"
abbr --add kgpvcwall "kubectl get pvc --watch --all-namespaces"
abbr --add kgnadwall "kubectl get net-attach-def --watch --all-namespaces"
abbr --add kgrswall "kubectl get replicaset --watch --all-namespaces"
abbr --add kgnswall "kubectl get namespaces --watch --all-namespaces"
abbr --add kgslw "kubectl get --show-labels --watch"
abbr --add ksysgslw "kubectl --namespace=kube-system get --show-labels --watch"
abbr --add kgposlw "kubectl get pods --show-labels --watch"
abbr --add ksysgposlw "kubectl --namespace=kube-system get pods --show-labels --watch"
abbr --add kgdepslw "kubectl get deployment --show-labels --watch"
abbr --add ksysgdepslw "kubectl --namespace=kube-system get deployment --show-labels --watch"
abbr --add kgdsslw "kubectl get daemonset --show-labels --watch"
abbr --add ksysgdsslw "kubectl --namespace=kube-system get daemonset --show-labels --watch"
abbr --add kgsvcslw "kubectl get service --show-labels --watch"
abbr --add ksysgsvcslw "kubectl --namespace=kube-system get service --show-labels --watch"
abbr --add kgingslw "kubectl get ingress --show-labels --watch"
abbr --add ksysgingslw "kubectl --namespace=kube-system get ingress --show-labels --watch"
abbr --add kgcmslw "kubectl get configmap --show-labels --watch"
abbr --add ksysgcmslw "kubectl --namespace=kube-system get configmap --show-labels --watch"
abbr --add kgsecslw "kubectl get secret --show-labels --watch"
abbr --add ksysgsecslw "kubectl --namespace=kube-system get secret --show-labels --watch"
abbr --add kgpvcslw "kubectl get pvc --show-labels --watch"
abbr --add ksysgpvcslw "kubectl --namespace=kube-system get pvc --show-labels --watch"
abbr --add kgnadslw "kubectl get net-attach-def --show-labels --watch"
abbr --add ksysgnadslw "kubectl --namespace=kube-system get net-attach-def --show-labels --watch"
abbr --add kgnoslw "kubectl get nodes --show-labels --watch"
abbr --add kgrsslw "kubectl get replicaset --show-labels --watch"
abbr --add kgnsslw "kubectl get namespaces --show-labels --watch"
abbr --add kgwsl "kubectl get --watch --show-labels"
abbr --add ksysgwsl "kubectl --namespace=kube-system get --watch --show-labels"
abbr --add kgpowsl "kubectl get pods --watch --show-labels"
abbr --add ksysgpowsl "kubectl --namespace=kube-system get pods --watch --show-labels"
abbr --add kgdepwsl "kubectl get deployment --watch --show-labels"
abbr --add ksysgdepwsl "kubectl --namespace=kube-system get deployment --watch --show-labels"
abbr --add kgdswsl "kubectl get daemonset --watch --show-labels"
abbr --add ksysgdswsl "kubectl --namespace=kube-system get daemonset --watch --show-labels"
abbr --add kgsvcwsl "kubectl get service --watch --show-labels"
abbr --add ksysgsvcwsl "kubectl --namespace=kube-system get service --watch --show-labels"
abbr --add kgingwsl "kubectl get ingress --watch --show-labels"
abbr --add ksysgingwsl "kubectl --namespace=kube-system get ingress --watch --show-labels"
abbr --add kgcmwsl "kubectl get configmap --watch --show-labels"
abbr --add ksysgcmwsl "kubectl --namespace=kube-system get configmap --watch --show-labels"
abbr --add kgsecwsl "kubectl get secret --watch --show-labels"
abbr --add ksysgsecwsl "kubectl --namespace=kube-system get secret --watch --show-labels"
abbr --add kgpvcwsl "kubectl get pvc --watch --show-labels"
abbr --add ksysgpvcwsl "kubectl --namespace=kube-system get pvc --watch --show-labels"
abbr --add kgnadwsl "kubectl get net-attach-def --watch --show-labels"
abbr --add ksysgnadwsl "kubectl --namespace=kube-system get net-attach-def --watch --show-labels"
abbr --add kgnowsl "kubectl get nodes --watch --show-labels"
abbr --add kgrswsl "kubectl get replicaset --watch --show-labels"
abbr --add kgnswsl "kubectl get namespaces --watch --show-labels"
abbr --add kgowideallsl "kubectl get -o=wide --all-namespaces --show-labels"
abbr --add kgpoowideallsl "kubectl get pods -o=wide --all-namespaces --show-labels"
abbr --add kgdepowideallsl "kubectl get deployment -o=wide --all-namespaces --show-labels"
abbr --add kgdsowideallsl "kubectl get daemonset -o=wide --all-namespaces --show-labels"
abbr --add kgsvcowideallsl "kubectl get service -o=wide --all-namespaces --show-labels"
abbr --add kgingowideallsl "kubectl get ingress -o=wide --all-namespaces --show-labels"
abbr --add kgcmowideallsl "kubectl get configmap -o=wide --all-namespaces --show-labels"
abbr --add kgsecowideallsl "kubectl get secret -o=wide --all-namespaces --show-labels"
abbr --add kgpvcowideallsl "kubectl get pvc -o=wide --all-namespaces --show-labels"
abbr --add kgnadowideallsl "kubectl get net-attach-def -o=wide --all-namespaces --show-labels"
abbr --add kgrsowideallsl "kubectl get replicaset -o=wide --all-namespaces --show-labels"
abbr --add kgnsowideallsl "kubectl get namespaces -o=wide --all-namespaces --show-labels"
abbr --add kgowideslall "kubectl get -o=wide --show-labels --all-namespaces"
abbr --add kgpoowideslall "kubectl get pods -o=wide --show-labels --all-namespaces"
abbr --add kgdepowideslall "kubectl get deployment -o=wide --show-labels --all-namespaces"
abbr --add kgdsowideslall "kubectl get daemonset -o=wide --show-labels --all-namespaces"
abbr --add kgsvcowideslall "kubectl get service -o=wide --show-labels --all-namespaces"
abbr --add kgingowideslall "kubectl get ingress -o=wide --show-labels --all-namespaces"
abbr --add kgcmowideslall "kubectl get configmap -o=wide --show-labels --all-namespaces"
abbr --add kgsecowideslall "kubectl get secret -o=wide --show-labels --all-namespaces"
abbr --add kgpvcowideslall "kubectl get pvc -o=wide --show-labels --all-namespaces"
abbr --add kgnadowideslall "kubectl get net-attach-def -o=wide --show-labels --all-namespaces"
abbr --add kgrsowideslall "kubectl get replicaset -o=wide --show-labels --all-namespaces"
abbr --add kgnsowideslall "kubectl get namespaces -o=wide --show-labels --all-namespaces"
abbr --add kgallowidesl "kubectl get --all-namespaces -o=wide --show-labels"
abbr --add kgpoallowidesl "kubectl get pods --all-namespaces -o=wide --show-labels"
abbr --add kgdepallowidesl "kubectl get deployment --all-namespaces -o=wide --show-labels"
abbr --add kgdsallowidesl "kubectl get daemonset --all-namespaces -o=wide --show-labels"
abbr --add kgsvcallowidesl "kubectl get service --all-namespaces -o=wide --show-labels"
abbr --add kgingallowidesl "kubectl get ingress --all-namespaces -o=wide --show-labels"
abbr --add kgcmallowidesl "kubectl get configmap --all-namespaces -o=wide --show-labels"
abbr --add kgsecallowidesl "kubectl get secret --all-namespaces -o=wide --show-labels"
abbr --add kgpvcallowidesl "kubectl get pvc --all-namespaces -o=wide --show-labels"
abbr --add kgnadallowidesl "kubectl get net-attach-def --all-namespaces -o=wide --show-labels"
abbr --add kgrsallowidesl "kubectl get replicaset --all-namespaces -o=wide --show-labels"
abbr --add kgnsallowidesl "kubectl get namespaces --all-namespaces -o=wide --show-labels"
abbr --add kgallslowide "kubectl get --all-namespaces --show-labels -o=wide"
abbr --add kgpoallslowide "kubectl get pods --all-namespaces --show-labels -o=wide"
abbr --add kgdepallslowide "kubectl get deployment --all-namespaces --show-labels -o=wide"
abbr --add kgdsallslowide "kubectl get daemonset --all-namespaces --show-labels -o=wide"
abbr --add kgsvcallslowide "kubectl get service --all-namespaces --show-labels -o=wide"
abbr --add kgingallslowide "kubectl get ingress --all-namespaces --show-labels -o=wide"
abbr --add kgcmallslowide "kubectl get configmap --all-namespaces --show-labels -o=wide"
abbr --add kgsecallslowide "kubectl get secret --all-namespaces --show-labels -o=wide"
abbr --add kgpvcallslowide "kubectl get pvc --all-namespaces --show-labels -o=wide"
abbr --add kgnadallslowide "kubectl get net-attach-def --all-namespaces --show-labels -o=wide"
abbr --add kgrsallslowide "kubectl get replicaset --all-namespaces --show-labels -o=wide"
abbr --add kgnsallslowide "kubectl get namespaces --all-namespaces --show-labels -o=wide"
abbr --add kgslowideall "kubectl get --show-labels -o=wide --all-namespaces"
abbr --add kgposlowideall "kubectl get pods --show-labels -o=wide --all-namespaces"
abbr --add kgdepslowideall "kubectl get deployment --show-labels -o=wide --all-namespaces"
abbr --add kgdsslowideall "kubectl get daemonset --show-labels -o=wide --all-namespaces"
abbr --add kgsvcslowideall "kubectl get service --show-labels -o=wide --all-namespaces"
abbr --add kgingslowideall "kubectl get ingress --show-labels -o=wide --all-namespaces"
abbr --add kgcmslowideall "kubectl get configmap --show-labels -o=wide --all-namespaces"
abbr --add kgsecslowideall "kubectl get secret --show-labels -o=wide --all-namespaces"
abbr --add kgpvcslowideall "kubectl get pvc --show-labels -o=wide --all-namespaces"
abbr --add kgnadslowideall "kubectl get net-attach-def --show-labels -o=wide --all-namespaces"
abbr --add kgrsslowideall "kubectl get replicaset --show-labels -o=wide --all-namespaces"
abbr --add kgnsslowideall "kubectl get namespaces --show-labels -o=wide --all-namespaces"
abbr --add kgslallowide "kubectl get --show-labels --all-namespaces -o=wide"
abbr --add kgposlallowide "kubectl get pods --show-labels --all-namespaces -o=wide"
abbr --add kgdepslallowide "kubectl get deployment --show-labels --all-namespaces -o=wide"
abbr --add kgdsslallowide "kubectl get daemonset --show-labels --all-namespaces -o=wide"
abbr --add kgsvcslallowide "kubectl get service --show-labels --all-namespaces -o=wide"
abbr --add kgingslallowide "kubectl get ingress --show-labels --all-namespaces -o=wide"
abbr --add kgcmslallowide "kubectl get configmap --show-labels --all-namespaces -o=wide"
abbr --add kgsecslallowide "kubectl get secret --show-labels --all-namespaces -o=wide"
abbr --add kgpvcslallowide "kubectl get pvc --show-labels --all-namespaces -o=wide"
abbr --add kgnadslallowide "kubectl get net-attach-def --show-labels --all-namespaces -o=wide"
abbr --add kgrsslallowide "kubectl get replicaset --show-labels --all-namespaces -o=wide"
abbr --add kgnsslallowide "kubectl get namespaces --show-labels --all-namespaces -o=wide"
abbr --add kgallslw "kubectl get --all-namespaces --show-labels --watch"
abbr --add kgpoallslw "kubectl get pods --all-namespaces --show-labels --watch"
abbr --add kgdepallslw "kubectl get deployment --all-namespaces --show-labels --watch"
abbr --add kgdsallslw "kubectl get daemonset --all-namespaces --show-labels --watch"
abbr --add kgsvcallslw "kubectl get service --all-namespaces --show-labels --watch"
abbr --add kgingallslw "kubectl get ingress --all-namespaces --show-labels --watch"
abbr --add kgcmallslw "kubectl get configmap --all-namespaces --show-labels --watch"
abbr --add kgsecallslw "kubectl get secret --all-namespaces --show-labels --watch"
abbr --add kgpvcallslw "kubectl get pvc --all-namespaces --show-labels --watch"
abbr --add kgnadallslw "kubectl get net-attach-def --all-namespaces --show-labels --watch"
abbr --add kgrsallslw "kubectl get replicaset --all-namespaces --show-labels --watch"
abbr --add kgnsallslw "kubectl get namespaces --all-namespaces --show-labels --watch"
abbr --add kgallwsl "kubectl get --all-namespaces --watch --show-labels"
abbr --add kgpoallwsl "kubectl get pods --all-namespaces --watch --show-labels"
abbr --add kgdepallwsl "kubectl get deployment --all-namespaces --watch --show-labels"
abbr --add kgdsallwsl "kubectl get daemonset --all-namespaces --watch --show-labels"
abbr --add kgsvcallwsl "kubectl get service --all-namespaces --watch --show-labels"
abbr --add kgingallwsl "kubectl get ingress --all-namespaces --watch --show-labels"
abbr --add kgcmallwsl "kubectl get configmap --all-namespaces --watch --show-labels"
abbr --add kgsecallwsl "kubectl get secret --all-namespaces --watch --show-labels"
abbr --add kgpvcallwsl "kubectl get pvc --all-namespaces --watch --show-labels"
abbr --add kgnadallwsl "kubectl get net-attach-def --all-namespaces --watch --show-labels"
abbr --add kgrsallwsl "kubectl get replicaset --all-namespaces --watch --show-labels"
abbr --add kgnsallwsl "kubectl get namespaces --all-namespaces --watch --show-labels"
abbr --add kgslallw "kubectl get --show-labels --all-namespaces --watch"
abbr --add kgposlallw "kubectl get pods --show-labels --all-namespaces --watch"
abbr --add kgdepslallw "kubectl get deployment --show-labels --all-namespaces --watch"
abbr --add kgdsslallw "kubectl get daemonset --show-labels --all-namespaces --watch"
abbr --add kgsvcslallw "kubectl get service --show-labels --all-namespaces --watch"
abbr --add kgingslallw "kubectl get ingress --show-labels --all-namespaces --watch"
abbr --add kgcmslallw "kubectl get configmap --show-labels --all-namespaces --watch"
abbr --add kgsecslallw "kubectl get secret --show-labels --all-namespaces --watch"
abbr --add kgpvcslallw "kubectl get pvc --show-labels --all-namespaces --watch"
abbr --add kgnadslallw "kubectl get net-attach-def --show-labels --all-namespaces --watch"
abbr --add kgrsslallw "kubectl get replicaset --show-labels --all-namespaces --watch"
abbr --add kgnsslallw "kubectl get namespaces --show-labels --all-namespaces --watch"
abbr --add kgslwall "kubectl get --show-labels --watch --all-namespaces"
abbr --add kgposlwall "kubectl get pods --show-labels --watch --all-namespaces"
abbr --add kgdepslwall "kubectl get deployment --show-labels --watch --all-namespaces"
abbr --add kgdsslwall "kubectl get daemonset --show-labels --watch --all-namespaces"
abbr --add kgsvcslwall "kubectl get service --show-labels --watch --all-namespaces"
abbr --add kgingslwall "kubectl get ingress --show-labels --watch --all-namespaces"
abbr --add kgcmslwall "kubectl get configmap --show-labels --watch --all-namespaces"
abbr --add kgsecslwall "kubectl get secret --show-labels --watch --all-namespaces"
abbr --add kgpvcslwall "kubectl get pvc --show-labels --watch --all-namespaces"
abbr --add kgnadslwall "kubectl get net-attach-def --show-labels --watch --all-namespaces"
abbr --add kgrsslwall "kubectl get replicaset --show-labels --watch --all-namespaces"
abbr --add kgnsslwall "kubectl get namespaces --show-labels --watch --all-namespaces"
abbr --add kgwallsl "kubectl get --watch --all-namespaces --show-labels"
abbr --add kgpowallsl "kubectl get pods --watch --all-namespaces --show-labels"
abbr --add kgdepwallsl "kubectl get deployment --watch --all-namespaces --show-labels"
abbr --add kgdswallsl "kubectl get daemonset --watch --all-namespaces --show-labels"
abbr --add kgsvcwallsl "kubectl get service --watch --all-namespaces --show-labels"
abbr --add kgingwallsl "kubectl get ingress --watch --all-namespaces --show-labels"
abbr --add kgcmwallsl "kubectl get configmap --watch --all-namespaces --show-labels"
abbr --add kgsecwallsl "kubectl get secret --watch --all-namespaces --show-labels"
abbr --add kgpvcwallsl "kubectl get pvc --watch --all-namespaces --show-labels"
abbr --add kgnadwallsl "kubectl get net-attach-def --watch --all-namespaces --show-labels"
abbr --add kgrswallsl "kubectl get replicaset --watch --all-namespaces --show-labels"
abbr --add kgnswallsl "kubectl get namespaces --watch --all-namespaces --show-labels"
abbr --add kgwslall "kubectl get --watch --show-labels --all-namespaces"
abbr --add kgpowslall "kubectl get pods --watch --show-labels --all-namespaces"
abbr --add kgdepwslall "kubectl get deployment --watch --show-labels --all-namespaces"
abbr --add kgdswslall "kubectl get daemonset --watch --show-labels --all-namespaces"
abbr --add kgsvcwslall "kubectl get service --watch --show-labels --all-namespaces"
abbr --add kgingwslall "kubectl get ingress --watch --show-labels --all-namespaces"
abbr --add kgcmwslall "kubectl get configmap --watch --show-labels --all-namespaces"
abbr --add kgsecwslall "kubectl get secret --watch --show-labels --all-namespaces"
abbr --add kgpvcwslall "kubectl get pvc --watch --show-labels --all-namespaces"
abbr --add kgnadwslall "kubectl get net-attach-def --watch --show-labels --all-namespaces"
abbr --add kgrswslall "kubectl get replicaset --watch --show-labels --all-namespaces"
abbr --add kgnswslall "kubectl get namespaces --watch --show-labels --all-namespaces"
abbr --add kgf "kubectl get --recursive -f"
abbr --add kdf "kubectl describe --recursive -f"
abbr --add krmf "kubectl delete --recursive -f"
abbr --add kgoyamlf "kubectl get -o=yaml --recursive -f"
abbr --add kgowidef "kubectl get -o=wide --recursive -f"
abbr --add kgojsonf "kubectl get -o=json --recursive -f"
abbr --add kgslf "kubectl get --show-labels --recursive -f"
abbr --add kgwf "kubectl get --watch --recursive -f"
abbr --add kgowideslf "kubectl get -o=wide --show-labels --recursive -f"
abbr --add kgslowidef "kubectl get --show-labels -o=wide --recursive -f"
abbr --add kgslwf "kubectl get --show-labels --watch --recursive -f"
abbr --add kgwslf "kubectl get --watch --show-labels --recursive -f"
abbr --add kgl "kubectl get -l"
abbr --add ksysgl "kubectl --namespace=kube-system get -l"
abbr --add kdl "kubectl describe -l"
abbr --add ksysdl "kubectl --namespace=kube-system describe -l"
abbr --add krml "kubectl delete -l"
abbr --add ksysrml "kubectl --namespace=kube-system delete -l"
abbr --add kgpol "kubectl get pods -l"
abbr --add ksysgpol "kubectl --namespace=kube-system get pods -l"
abbr --add kdpol "kubectl describe pods -l"
abbr --add ksysdpol "kubectl --namespace=kube-system describe pods -l"
abbr --add krmpol "kubectl delete pods -l"
abbr --add ksysrmpol "kubectl --namespace=kube-system delete pods -l"
abbr --add kgdepl "kubectl get deployment -l"
abbr --add ksysgdepl "kubectl --namespace=kube-system get deployment -l"
abbr --add kddepl "kubectl describe deployment -l"
abbr --add ksysddepl "kubectl --namespace=kube-system describe deployment -l"
abbr --add krmdepl "kubectl delete deployment -l"
abbr --add ksysrmdepl "kubectl --namespace=kube-system delete deployment -l"
abbr --add kgdsl "kubectl get daemonset -l"
abbr --add ksysgdsl "kubectl --namespace=kube-system get daemonset -l"
abbr --add kddsl "kubectl describe daemonset -l"
abbr --add ksysddsl "kubectl --namespace=kube-system describe daemonset -l"
abbr --add krmdsl "kubectl delete daemonset -l"
abbr --add ksysrmdsl "kubectl --namespace=kube-system delete daemonset -l"
abbr --add kgsvcl "kubectl get service -l"
abbr --add ksysgsvcl "kubectl --namespace=kube-system get service -l"
abbr --add kdsvcl "kubectl describe service -l"
abbr --add ksysdsvcl "kubectl --namespace=kube-system describe service -l"
abbr --add krmsvcl "kubectl delete service -l"
abbr --add ksysrmsvcl "kubectl --namespace=kube-system delete service -l"
abbr --add kgingl "kubectl get ingress -l"
abbr --add ksysgingl "kubectl --namespace=kube-system get ingress -l"
abbr --add kdingl "kubectl describe ingress -l"
abbr --add ksysdingl "kubectl --namespace=kube-system describe ingress -l"
abbr --add krmingl "kubectl delete ingress -l"
abbr --add ksysrmingl "kubectl --namespace=kube-system delete ingress -l"
abbr --add kgcml "kubectl get configmap -l"
abbr --add ksysgcml "kubectl --namespace=kube-system get configmap -l"
abbr --add kdcml "kubectl describe configmap -l"
abbr --add ksysdcml "kubectl --namespace=kube-system describe configmap -l"
abbr --add krmcml "kubectl delete configmap -l"
abbr --add ksysrmcml "kubectl --namespace=kube-system delete configmap -l"
abbr --add kgsecl "kubectl get secret -l"
abbr --add ksysgsecl "kubectl --namespace=kube-system get secret -l"
abbr --add kdsecl "kubectl describe secret -l"
abbr --add ksysdsecl "kubectl --namespace=kube-system describe secret -l"
abbr --add krmsecl "kubectl delete secret -l"
abbr --add ksysrmsecl "kubectl --namespace=kube-system delete secret -l"
abbr --add kgpvcl "kubectl get pvc -l"
abbr --add ksysgpvcl "kubectl --namespace=kube-system get pvc -l"
abbr --add kdpvcl "kubectl describe pvc -l"
abbr --add ksysdpvcl "kubectl --namespace=kube-system describe pvc -l"
abbr --add krmpvcl "kubectl delete pvc -l"
abbr --add ksysrmpvcl "kubectl --namespace=kube-system delete pvc -l"
abbr --add kgnadl "kubectl get net-attach-def -l"
abbr --add ksysgnadl "kubectl --namespace=kube-system get net-attach-def -l"
abbr --add kdnadl "kubectl describe net-attach-def -l"
abbr --add ksysdnadl "kubectl --namespace=kube-system describe net-attach-def -l"
abbr --add krmnadl "kubectl delete net-attach-def -l"
abbr --add ksysrmnadl "kubectl --namespace=kube-system delete net-attach-def -l"
abbr --add kgnol "kubectl get nodes -l"
abbr --add kdnol "kubectl describe nodes -l"
abbr --add kgrsl "kubectl get replicaset -l"
abbr --add kdrsl "kubectl describe replicaset -l"
abbr --add kgnsl "kubectl get namespaces -l"
abbr --add kdnsl "kubectl describe namespaces -l"
abbr --add krmnsl "kubectl delete namespaces -l"
abbr --add kgoyamll "kubectl get -o=yaml -l"
abbr --add ksysgoyamll "kubectl --namespace=kube-system get -o=yaml -l"
abbr --add kgpooyamll "kubectl get pods -o=yaml -l"
abbr --add ksysgpooyamll "kubectl --namespace=kube-system get pods -o=yaml -l"
abbr --add kgdepoyamll "kubectl get deployment -o=yaml -l"
abbr --add ksysgdepoyamll "kubectl --namespace=kube-system get deployment -o=yaml -l"
abbr --add kgdsoyamll "kubectl get daemonset -o=yaml -l"
abbr --add ksysgdsoyamll "kubectl --namespace=kube-system get daemonset -o=yaml -l"
abbr --add kgsvcoyamll "kubectl get service -o=yaml -l"
abbr --add ksysgsvcoyamll "kubectl --namespace=kube-system get service -o=yaml -l"
abbr --add kgingoyamll "kubectl get ingress -o=yaml -l"
abbr --add ksysgingoyamll "kubectl --namespace=kube-system get ingress -o=yaml -l"
abbr --add kgcmoyamll "kubectl get configmap -o=yaml -l"
abbr --add ksysgcmoyamll "kubectl --namespace=kube-system get configmap -o=yaml -l"
abbr --add kgsecoyamll "kubectl get secret -o=yaml -l"
abbr --add ksysgsecoyamll "kubectl --namespace=kube-system get secret -o=yaml -l"
abbr --add kgpvcoyamll "kubectl get pvc -o=yaml -l"
abbr --add ksysgpvcoyamll "kubectl --namespace=kube-system get pvc -o=yaml -l"
abbr --add kgnadoyamll "kubectl get net-attach-def -o=yaml -l"
abbr --add ksysgnadoyamll "kubectl --namespace=kube-system get net-attach-def -o=yaml -l"
abbr --add kgnooyamll "kubectl get nodes -o=yaml -l"
abbr --add kgrsoyamll "kubectl get replicaset -o=yaml -l"
abbr --add kgnsoyamll "kubectl get namespaces -o=yaml -l"
abbr --add kgowidel "kubectl get -o=wide -l"
abbr --add ksysgowidel "kubectl --namespace=kube-system get -o=wide -l"
abbr --add kgpoowidel "kubectl get pods -o=wide -l"
abbr --add ksysgpoowidel "kubectl --namespace=kube-system get pods -o=wide -l"
abbr --add kgdepowidel "kubectl get deployment -o=wide -l"
abbr --add ksysgdepowidel "kubectl --namespace=kube-system get deployment -o=wide -l"
abbr --add kgdsowidel "kubectl get daemonset -o=wide -l"
abbr --add ksysgdsowidel "kubectl --namespace=kube-system get daemonset -o=wide -l"
abbr --add kgsvcowidel "kubectl get service -o=wide -l"
abbr --add ksysgsvcowidel "kubectl --namespace=kube-system get service -o=wide -l"
abbr --add kgingowidel "kubectl get ingress -o=wide -l"
abbr --add ksysgingowidel "kubectl --namespace=kube-system get ingress -o=wide -l"
abbr --add kgcmowidel "kubectl get configmap -o=wide -l"
abbr --add ksysgcmowidel "kubectl --namespace=kube-system get configmap -o=wide -l"
abbr --add kgsecowidel "kubectl get secret -o=wide -l"
abbr --add ksysgsecowidel "kubectl --namespace=kube-system get secret -o=wide -l"
abbr --add kgpvcowidel "kubectl get pvc -o=wide -l"
abbr --add ksysgpvcowidel "kubectl --namespace=kube-system get pvc -o=wide -l"
abbr --add kgnadowidel "kubectl get net-attach-def -o=wide -l"
abbr --add ksysgnadowidel "kubectl --namespace=kube-system get net-attach-def -o=wide -l"
abbr --add kgnoowidel "kubectl get nodes -o=wide -l"
abbr --add kgrsowidel "kubectl get replicaset -o=wide -l"
abbr --add kgnsowidel "kubectl get namespaces -o=wide -l"
abbr --add kgojsonl "kubectl get -o=json -l"
abbr --add ksysgojsonl "kubectl --namespace=kube-system get -o=json -l"
abbr --add kgpoojsonl "kubectl get pods -o=json -l"
abbr --add ksysgpoojsonl "kubectl --namespace=kube-system get pods -o=json -l"
abbr --add kgdepojsonl "kubectl get deployment -o=json -l"
abbr --add ksysgdepojsonl "kubectl --namespace=kube-system get deployment -o=json -l"
abbr --add kgdsojsonl "kubectl get daemonset -o=json -l"
abbr --add ksysgdsojsonl "kubectl --namespace=kube-system get daemonset -o=json -l"
abbr --add kgsvcojsonl "kubectl get service -o=json -l"
abbr --add ksysgsvcojsonl "kubectl --namespace=kube-system get service -o=json -l"
abbr --add kgingojsonl "kubectl get ingress -o=json -l"
abbr --add ksysgingojsonl "kubectl --namespace=kube-system get ingress -o=json -l"
abbr --add kgcmojsonl "kubectl get configmap -o=json -l"
abbr --add ksysgcmojsonl "kubectl --namespace=kube-system get configmap -o=json -l"
abbr --add kgsecojsonl "kubectl get secret -o=json -l"
abbr --add ksysgsecojsonl "kubectl --namespace=kube-system get secret -o=json -l"
abbr --add kgpvcojsonl "kubectl get pvc -o=json -l"
abbr --add ksysgpvcojsonl "kubectl --namespace=kube-system get pvc -o=json -l"
abbr --add kgnadojsonl "kubectl get net-attach-def -o=json -l"
abbr --add ksysgnadojsonl "kubectl --namespace=kube-system get net-attach-def -o=json -l"
abbr --add kgnoojsonl "kubectl get nodes -o=json -l"
abbr --add kgrsojsonl "kubectl get replicaset -o=json -l"
abbr --add kgnsojsonl "kubectl get namespaces -o=json -l"
abbr --add kgsll "kubectl get --show-labels -l"
abbr --add ksysgsll "kubectl --namespace=kube-system get --show-labels -l"
abbr --add kgposll "kubectl get pods --show-labels -l"
abbr --add ksysgposll "kubectl --namespace=kube-system get pods --show-labels -l"
abbr --add kgdepsll "kubectl get deployment --show-labels -l"
abbr --add ksysgdepsll "kubectl --namespace=kube-system get deployment --show-labels -l"
abbr --add kgdssll "kubectl get daemonset --show-labels -l"
abbr --add ksysgdssll "kubectl --namespace=kube-system get daemonset --show-labels -l"
abbr --add kgsvcsll "kubectl get service --show-labels -l"
abbr --add ksysgsvcsll "kubectl --namespace=kube-system get service --show-labels -l"
abbr --add kgingsll "kubectl get ingress --show-labels -l"
abbr --add ksysgingsll "kubectl --namespace=kube-system get ingress --show-labels -l"
abbr --add kgcmsll "kubectl get configmap --show-labels -l"
abbr --add ksysgcmsll "kubectl --namespace=kube-system get configmap --show-labels -l"
abbr --add kgsecsll "kubectl get secret --show-labels -l"
abbr --add ksysgsecsll "kubectl --namespace=kube-system get secret --show-labels -l"
abbr --add kgpvcsll "kubectl get pvc --show-labels -l"
abbr --add ksysgpvcsll "kubectl --namespace=kube-system get pvc --show-labels -l"
abbr --add kgnadsll "kubectl get net-attach-def --show-labels -l"
abbr --add ksysgnadsll "kubectl --namespace=kube-system get net-attach-def --show-labels -l"
abbr --add kgnosll "kubectl get nodes --show-labels -l"
abbr --add kgrssll "kubectl get replicaset --show-labels -l"
abbr --add kgnssll "kubectl get namespaces --show-labels -l"
abbr --add kgwl "kubectl get --watch -l"
abbr --add ksysgwl "kubectl --namespace=kube-system get --watch -l"
abbr --add kgpowl "kubectl get pods --watch -l"
abbr --add ksysgpowl "kubectl --namespace=kube-system get pods --watch -l"
abbr --add kgdepwl "kubectl get deployment --watch -l"
abbr --add ksysgdepwl "kubectl --namespace=kube-system get deployment --watch -l"
abbr --add kgdswl "kubectl get daemonset --watch -l"
abbr --add ksysgdswl "kubectl --namespace=kube-system get daemonset --watch -l"
abbr --add kgsvcwl "kubectl get service --watch -l"
abbr --add ksysgsvcwl "kubectl --namespace=kube-system get service --watch -l"
abbr --add kgingwl "kubectl get ingress --watch -l"
abbr --add ksysgingwl "kubectl --namespace=kube-system get ingress --watch -l"
abbr --add kgcmwl "kubectl get configmap --watch -l"
abbr --add ksysgcmwl "kubectl --namespace=kube-system get configmap --watch -l"
abbr --add kgsecwl "kubectl get secret --watch -l"
abbr --add ksysgsecwl "kubectl --namespace=kube-system get secret --watch -l"
abbr --add kgpvcwl "kubectl get pvc --watch -l"
abbr --add ksysgpvcwl "kubectl --namespace=kube-system get pvc --watch -l"
abbr --add kgnadwl "kubectl get net-attach-def --watch -l"
abbr --add ksysgnadwl "kubectl --namespace=kube-system get net-attach-def --watch -l"
abbr --add kgnowl "kubectl get nodes --watch -l"
abbr --add kgrswl "kubectl get replicaset --watch -l"
abbr --add kgnswl "kubectl get namespaces --watch -l"
abbr --add kgowidesll "kubectl get -o=wide --show-labels -l"
abbr --add ksysgowidesll "kubectl --namespace=kube-system get -o=wide --show-labels -l"
abbr --add kgpoowidesll "kubectl get pods -o=wide --show-labels -l"
abbr --add ksysgpoowidesll "kubectl --namespace=kube-system get pods -o=wide --show-labels -l"
abbr --add kgdepowidesll "kubectl get deployment -o=wide --show-labels -l"
abbr --add ksysgdepowidesll "kubectl --namespace=kube-system get deployment -o=wide --show-labels -l"
abbr --add kgdsowidesll "kubectl get daemonset -o=wide --show-labels -l"
abbr --add ksysgdsowidesll "kubectl --namespace=kube-system get daemonset -o=wide --show-labels -l"
abbr --add kgsvcowidesll "kubectl get service -o=wide --show-labels -l"
abbr --add ksysgsvcowidesll "kubectl --namespace=kube-system get service -o=wide --show-labels -l"
abbr --add kgingowidesll "kubectl get ingress -o=wide --show-labels -l"
abbr --add ksysgingowidesll "kubectl --namespace=kube-system get ingress -o=wide --show-labels -l"
abbr --add kgcmowidesll "kubectl get configmap -o=wide --show-labels -l"
abbr --add ksysgcmowidesll "kubectl --namespace=kube-system get configmap -o=wide --show-labels -l"
abbr --add kgsecowidesll "kubectl get secret -o=wide --show-labels -l"
abbr --add ksysgsecowidesll "kubectl --namespace=kube-system get secret -o=wide --show-labels -l"
abbr --add kgpvcowidesll "kubectl get pvc -o=wide --show-labels -l"
abbr --add ksysgpvcowidesll "kubectl --namespace=kube-system get pvc -o=wide --show-labels -l"
abbr --add kgnadowidesll "kubectl get net-attach-def -o=wide --show-labels -l"
abbr --add ksysgnadowidesll "kubectl --namespace=kube-system get net-attach-def -o=wide --show-labels -l"
abbr --add kgnoowidesll "kubectl get nodes -o=wide --show-labels -l"
abbr --add kgrsowidesll "kubectl get replicaset -o=wide --show-labels -l"
abbr --add kgnsowidesll "kubectl get namespaces -o=wide --show-labels -l"
abbr --add kgslowidel "kubectl get --show-labels -o=wide -l"
abbr --add ksysgslowidel "kubectl --namespace=kube-system get --show-labels -o=wide -l"
abbr --add kgposlowidel "kubectl get pods --show-labels -o=wide -l"
abbr --add ksysgposlowidel "kubectl --namespace=kube-system get pods --show-labels -o=wide -l"
abbr --add kgdepslowidel "kubectl get deployment --show-labels -o=wide -l"
abbr --add ksysgdepslowidel "kubectl --namespace=kube-system get deployment --show-labels -o=wide -l"
abbr --add kgdsslowidel "kubectl get daemonset --show-labels -o=wide -l"
abbr --add ksysgdsslowidel "kubectl --namespace=kube-system get daemonset --show-labels -o=wide -l"
abbr --add kgsvcslowidel "kubectl get service --show-labels -o=wide -l"
abbr --add ksysgsvcslowidel "kubectl --namespace=kube-system get service --show-labels -o=wide -l"
abbr --add kgingslowidel "kubectl get ingress --show-labels -o=wide -l"
abbr --add ksysgingslowidel "kubectl --namespace=kube-system get ingress --show-labels -o=wide -l"
abbr --add kgcmslowidel "kubectl get configmap --show-labels -o=wide -l"
abbr --add ksysgcmslowidel "kubectl --namespace=kube-system get configmap --show-labels -o=wide -l"
abbr --add kgsecslowidel "kubectl get secret --show-labels -o=wide -l"
abbr --add ksysgsecslowidel "kubectl --namespace=kube-system get secret --show-labels -o=wide -l"
abbr --add kgpvcslowidel "kubectl get pvc --show-labels -o=wide -l"
abbr --add ksysgpvcslowidel "kubectl --namespace=kube-system get pvc --show-labels -o=wide -l"
abbr --add kgnadslowidel "kubectl get net-attach-def --show-labels -o=wide -l"
abbr --add ksysgnadslowidel "kubectl --namespace=kube-system get net-attach-def --show-labels -o=wide -l"
abbr --add kgnoslowidel "kubectl get nodes --show-labels -o=wide -l"
abbr --add kgrsslowidel "kubectl get replicaset --show-labels -o=wide -l"
abbr --add kgnsslowidel "kubectl get namespaces --show-labels -o=wide -l"
abbr --add kgslwl "kubectl get --show-labels --watch -l"
abbr --add ksysgslwl "kubectl --namespace=kube-system get --show-labels --watch -l"
abbr --add kgposlwl "kubectl get pods --show-labels --watch -l"
abbr --add ksysgposlwl "kubectl --namespace=kube-system get pods --show-labels --watch -l"
abbr --add kgdepslwl "kubectl get deployment --show-labels --watch -l"
abbr --add ksysgdepslwl "kubectl --namespace=kube-system get deployment --show-labels --watch -l"
abbr --add kgdsslwl "kubectl get daemonset --show-labels --watch -l"
abbr --add ksysgdsslwl "kubectl --namespace=kube-system get daemonset --show-labels --watch -l"
abbr --add kgsvcslwl "kubectl get service --show-labels --watch -l"
abbr --add ksysgsvcslwl "kubectl --namespace=kube-system get service --show-labels --watch -l"
abbr --add kgingslwl "kubectl get ingress --show-labels --watch -l"
abbr --add ksysgingslwl "kubectl --namespace=kube-system get ingress --show-labels --watch -l"
abbr --add kgcmslwl "kubectl get configmap --show-labels --watch -l"
abbr --add ksysgcmslwl "kubectl --namespace=kube-system get configmap --show-labels --watch -l"
abbr --add kgsecslwl "kubectl get secret --show-labels --watch -l"
abbr --add ksysgsecslwl "kubectl --namespace=kube-system get secret --show-labels --watch -l"
abbr --add kgpvcslwl "kubectl get pvc --show-labels --watch -l"
abbr --add ksysgpvcslwl "kubectl --namespace=kube-system get pvc --show-labels --watch -l"
abbr --add kgnadslwl "kubectl get net-attach-def --show-labels --watch -l"
abbr --add ksysgnadslwl "kubectl --namespace=kube-system get net-attach-def --show-labels --watch -l"
abbr --add kgnoslwl "kubectl get nodes --show-labels --watch -l"
abbr --add kgrsslwl "kubectl get replicaset --show-labels --watch -l"
abbr --add kgnsslwl "kubectl get namespaces --show-labels --watch -l"
abbr --add kgwsll "kubectl get --watch --show-labels -l"
abbr --add ksysgwsll "kubectl --namespace=kube-system get --watch --show-labels -l"
abbr --add kgpowsll "kubectl get pods --watch --show-labels -l"
abbr --add ksysgpowsll "kubectl --namespace=kube-system get pods --watch --show-labels -l"
abbr --add kgdepwsll "kubectl get deployment --watch --show-labels -l"
abbr --add ksysgdepwsll "kubectl --namespace=kube-system get deployment --watch --show-labels -l"
abbr --add kgdswsll "kubectl get daemonset --watch --show-labels -l"
abbr --add ksysgdswsll "kubectl --namespace=kube-system get daemonset --watch --show-labels -l"
abbr --add kgsvcwsll "kubectl get service --watch --show-labels -l"
abbr --add ksysgsvcwsll "kubectl --namespace=kube-system get service --watch --show-labels -l"
abbr --add kgingwsll "kubectl get ingress --watch --show-labels -l"
abbr --add ksysgingwsll "kubectl --namespace=kube-system get ingress --watch --show-labels -l"
abbr --add kgcmwsll "kubectl get configmap --watch --show-labels -l"
abbr --add ksysgcmwsll "kubectl --namespace=kube-system get configmap --watch --show-labels -l"
abbr --add kgsecwsll "kubectl get secret --watch --show-labels -l"
abbr --add ksysgsecwsll "kubectl --namespace=kube-system get secret --watch --show-labels -l"
abbr --add kgpvcwsll "kubectl get pvc --watch --show-labels -l"
abbr --add ksysgpvcwsll "kubectl --namespace=kube-system get pvc --watch --show-labels -l"
abbr --add kgnadwsll "kubectl get net-attach-def --watch --show-labels -l"
abbr --add ksysgnadwsll "kubectl --namespace=kube-system get net-attach-def --watch --show-labels -l"
abbr --add kgnowsll "kubectl get nodes --watch --show-labels -l"
abbr --add kgrswsll "kubectl get replicaset --watch --show-labels -l"
abbr --add kgnswsll "kubectl get namespaces --watch --show-labels -l"
abbr --add kexn "kubectl exec -i -t --namespace"
abbr --add klon "kubectl logs -f --namespace"
abbr --add ken "kubectl edit --namespace"
abbr --add krrn "kubectl rollout restart --namespace"
abbr --add krsn "kubectl rollout status --namespace"
abbr --add ksn "kubectl scale --namespace"
abbr --add kpfn "kubectl port-forward --namespace"
abbr --add kgn "kubectl get --namespace"
abbr --add kdn "kubectl describe --namespace"
abbr --add krmn "kubectl delete --namespace"
abbr --add kepon "kubectl edit pods --namespace"
abbr --add kgpon "kubectl get pods --namespace"
abbr --add kdpon "kubectl describe pods --namespace"
abbr --add krmpon "kubectl delete pods --namespace"
abbr --add kedepn "kubectl edit deployment --namespace"
abbr --add krrdepn "kubectl rollout restart deployment --namespace"
abbr --add krsdepn "kubectl rollout status deployment --namespace"
abbr --add ksdepn "kubectl scale deployment --namespace"
abbr --add kgdepn "kubectl get deployment --namespace"
abbr --add kddepn "kubectl describe deployment --namespace"
abbr --add krmdepn "kubectl delete deployment --namespace"
abbr --add kedsn "kubectl edit daemonset --namespace"
abbr --add krrdsn "kubectl rollout restart daemonset --namespace"
abbr --add krsdsn "kubectl rollout status daemonset --namespace"
abbr --add kgdsn "kubectl get daemonset --namespace"
abbr --add kddsn "kubectl describe daemonset --namespace"
abbr --add krmdsn "kubectl delete daemonset --namespace"
abbr --add kesvcn "kubectl edit service --namespace"
abbr --add kgsvcn "kubectl get service --namespace"
abbr --add kdsvcn "kubectl describe service --namespace"
abbr --add krmsvcn "kubectl delete service --namespace"
abbr --add keingn "kubectl edit ingress --namespace"
abbr --add kgingn "kubectl get ingress --namespace"
abbr --add kdingn "kubectl describe ingress --namespace"
abbr --add krmingn "kubectl delete ingress --namespace"
abbr --add kecmn "kubectl edit configmap --namespace"
abbr --add kgcmn "kubectl get configmap --namespace"
abbr --add kdcmn "kubectl describe configmap --namespace"
abbr --add krmcmn "kubectl delete configmap --namespace"
abbr --add kesecn "kubectl edit secret --namespace"
abbr --add kgsecn "kubectl get secret --namespace"
abbr --add kdsecn "kubectl describe secret --namespace"
abbr --add krmsecn "kubectl delete secret --namespace"
abbr --add kgpvcn "kubectl get pvc --namespace"
abbr --add kdpvcn "kubectl describe pvc --namespace"
abbr --add krmpvcn "kubectl delete pvc --namespace"
abbr --add kgnadn "kubectl get net-attach-def --namespace"
abbr --add kdnadn "kubectl describe net-attach-def --namespace"
abbr --add krmnadn "kubectl delete net-attach-def --namespace"
abbr --add kgrsn "kubectl get replicaset --namespace"
abbr --add kdrsn "kubectl describe replicaset --namespace"
abbr --add kgoyamln "kubectl get -o=yaml --namespace"
abbr --add kgpooyamln "kubectl get pods -o=yaml --namespace"
abbr --add kgdepoyamln "kubectl get deployment -o=yaml --namespace"
abbr --add kgdsoyamln "kubectl get daemonset -o=yaml --namespace"
abbr --add kgsvcoyamln "kubectl get service -o=yaml --namespace"
abbr --add kgingoyamln "kubectl get ingress -o=yaml --namespace"
abbr --add kgcmoyamln "kubectl get configmap -o=yaml --namespace"
abbr --add kgsecoyamln "kubectl get secret -o=yaml --namespace"
abbr --add kgpvcoyamln "kubectl get pvc -o=yaml --namespace"
abbr --add kgnadoyamln "kubectl get net-attach-def -o=yaml --namespace"
abbr --add kgrsoyamln "kubectl get replicaset -o=yaml --namespace"
abbr --add kgowiden "kubectl get -o=wide --namespace"
abbr --add kgpoowiden "kubectl get pods -o=wide --namespace"
abbr --add kgdepowiden "kubectl get deployment -o=wide --namespace"
abbr --add kgdsowiden "kubectl get daemonset -o=wide --namespace"
abbr --add kgsvcowiden "kubectl get service -o=wide --namespace"
abbr --add kgingowiden "kubectl get ingress -o=wide --namespace"
abbr --add kgcmowiden "kubectl get configmap -o=wide --namespace"
abbr --add kgsecowiden "kubectl get secret -o=wide --namespace"
abbr --add kgpvcowiden "kubectl get pvc -o=wide --namespace"
abbr --add kgnadowiden "kubectl get net-attach-def -o=wide --namespace"
abbr --add kgrsowiden "kubectl get replicaset -o=wide --namespace"
abbr --add kgojsonn "kubectl get -o=json --namespace"
abbr --add kgpoojsonn "kubectl get pods -o=json --namespace"
abbr --add kgdepojsonn "kubectl get deployment -o=json --namespace"
abbr --add kgdsojsonn "kubectl get daemonset -o=json --namespace"
abbr --add kgsvcojsonn "kubectl get service -o=json --namespace"
abbr --add kgingojsonn "kubectl get ingress -o=json --namespace"
abbr --add kgcmojsonn "kubectl get configmap -o=json --namespace"
abbr --add kgsecojsonn "kubectl get secret -o=json --namespace"
abbr --add kgpvcojsonn "kubectl get pvc -o=json --namespace"
abbr --add kgnadojsonn "kubectl get net-attach-def -o=json --namespace"
abbr --add kgrsojsonn "kubectl get replicaset -o=json --namespace"
abbr --add kgsln "kubectl get --show-labels --namespace"
abbr --add kgposln "kubectl get pods --show-labels --namespace"
abbr --add kgdepsln "kubectl get deployment --show-labels --namespace"
abbr --add kgdssln "kubectl get daemonset --show-labels --namespace"
abbr --add kgsvcsln "kubectl get service --show-labels --namespace"
abbr --add kgingsln "kubectl get ingress --show-labels --namespace"
abbr --add kgcmsln "kubectl get configmap --show-labels --namespace"
abbr --add kgsecsln "kubectl get secret --show-labels --namespace"
abbr --add kgpvcsln "kubectl get pvc --show-labels --namespace"
abbr --add kgnadsln "kubectl get net-attach-def --show-labels --namespace"
abbr --add kgrssln "kubectl get replicaset --show-labels --namespace"
abbr --add kgwn "kubectl get --watch --namespace"
abbr --add kgpown "kubectl get pods --watch --namespace"
abbr --add kgdepwn "kubectl get deployment --watch --namespace"
abbr --add kgdswn "kubectl get daemonset --watch --namespace"
abbr --add kgsvcwn "kubectl get service --watch --namespace"
abbr --add kgingwn "kubectl get ingress --watch --namespace"
abbr --add kgcmwn "kubectl get configmap --watch --namespace"
abbr --add kgsecwn "kubectl get secret --watch --namespace"
abbr --add kgpvcwn "kubectl get pvc --watch --namespace"
abbr --add kgnadwn "kubectl get net-attach-def --watch --namespace"
abbr --add kgrswn "kubectl get replicaset --watch --namespace"
abbr --add kgowidesln "kubectl get -o=wide --show-labels --namespace"
abbr --add kgpoowidesln "kubectl get pods -o=wide --show-labels --namespace"
abbr --add kgdepowidesln "kubectl get deployment -o=wide --show-labels --namespace"
abbr --add kgdsowidesln "kubectl get daemonset -o=wide --show-labels --namespace"
abbr --add kgsvcowidesln "kubectl get service -o=wide --show-labels --namespace"
abbr --add kgingowidesln "kubectl get ingress -o=wide --show-labels --namespace"
abbr --add kgcmowidesln "kubectl get configmap -o=wide --show-labels --namespace"
abbr --add kgsecowidesln "kubectl get secret -o=wide --show-labels --namespace"
abbr --add kgpvcowidesln "kubectl get pvc -o=wide --show-labels --namespace"
abbr --add kgnadowidesln "kubectl get net-attach-def -o=wide --show-labels --namespace"
abbr --add kgrsowidesln "kubectl get replicaset -o=wide --show-labels --namespace"
abbr --add kgslowiden "kubectl get --show-labels -o=wide --namespace"
abbr --add kgposlowiden "kubectl get pods --show-labels -o=wide --namespace"
abbr --add kgdepslowiden "kubectl get deployment --show-labels -o=wide --namespace"
abbr --add kgdsslowiden "kubectl get daemonset --show-labels -o=wide --namespace"
abbr --add kgsvcslowiden "kubectl get service --show-labels -o=wide --namespace"
abbr --add kgingslowiden "kubectl get ingress --show-labels -o=wide --namespace"
abbr --add kgcmslowiden "kubectl get configmap --show-labels -o=wide --namespace"
abbr --add kgsecslowiden "kubectl get secret --show-labels -o=wide --namespace"
abbr --add kgpvcslowiden "kubectl get pvc --show-labels -o=wide --namespace"
abbr --add kgnadslowiden "kubectl get net-attach-def --show-labels -o=wide --namespace"
abbr --add kgrsslowiden "kubectl get replicaset --show-labels -o=wide --namespace"
abbr --add kgslwn "kubectl get --show-labels --watch --namespace"
abbr --add kgposlwn "kubectl get pods --show-labels --watch --namespace"
abbr --add kgdepslwn "kubectl get deployment --show-labels --watch --namespace"
abbr --add kgdsslwn "kubectl get daemonset --show-labels --watch --namespace"
abbr --add kgsvcslwn "kubectl get service --show-labels --watch --namespace"
abbr --add kgingslwn "kubectl get ingress --show-labels --watch --namespace"
abbr --add kgcmslwn "kubectl get configmap --show-labels --watch --namespace"
abbr --add kgsecslwn "kubectl get secret --show-labels --watch --namespace"
abbr --add kgpvcslwn "kubectl get pvc --show-labels --watch --namespace"
abbr --add kgnadslwn "kubectl get net-attach-def --show-labels --watch --namespace"
abbr --add kgrsslwn "kubectl get replicaset --show-labels --watch --namespace"
abbr --add kgwsln "kubectl get --watch --show-labels --namespace"
abbr --add kgpowsln "kubectl get pods --watch --show-labels --namespace"
abbr --add kgdepwsln "kubectl get deployment --watch --show-labels --namespace"
abbr --add kgdswsln "kubectl get daemonset --watch --show-labels --namespace"
abbr --add kgsvcwsln "kubectl get service --watch --show-labels --namespace"
abbr --add kgingwsln "kubectl get ingress --watch --show-labels --namespace"
abbr --add kgcmwsln "kubectl get configmap --watch --show-labels --namespace"
abbr --add kgsecwsln "kubectl get secret --watch --show-labels --namespace"
abbr --add kgpvcwsln "kubectl get pvc --watch --show-labels --namespace"
abbr --add kgnadwsln "kubectl get net-attach-def --watch --show-labels --namespace"
abbr --add kgrswsln "kubectl get replicaset --watch --show-labels --namespace"
abbr --add kswag "kubectl get --raw /openapi/v2  > /tmp/$KUBECONFIG-openapi-v2.json && docker run -v /tmp/$KUBECONFIG-openapi-v2.json:/app/swagger.json -p 8081:8080 swaggerapi/swagger-ui"
kubectl completion fish | source
